import { useState, useEffect, useRef, useMemo } from 'react'
import { buildShoppingList, enrichIngredientsWithQuantities, categorizeIngredient, consolidateQuantities } from '../utils/shopping'
import { getWeekRange, getWeekStart } from '../utils/format'

const CATEGORY_ORDER = [
  'Proteins & Meat', 'Seafood', 'Produce', 'Dairy & Eggs',
  'Pantry & Dry Goods', 'Herbs & Spices', 'Other'
]

// Collect all items that are checked (both auto and manual), deduplicated
function collectChecked(categories, manualItems, checked) {
  const seen = new Set()
  const items = []
  Object.values(categories).forEach(catItems => {
    catItems.filter(i => checked.has(i)).forEach(i => {
      if (!seen.has(i)) { seen.add(i); items.push(i) }
    })
  })
  manualItems.filter(m => checked.has(m.name)).forEach(m => {
    if (!seen.has(m.name)) { seen.add(m.name); items.push(m.name) }
  })
  return items
}

// Shared header: date + numbered meal list
function headerLines(range, mealObjects) {
  const lines = [`🛒 Shopping List — ${range}`, '']
  if (mealObjects.length > 0) {
    lines.push("🍽️ This Week's Meals:")
    mealObjects.forEach((m, i) => lines.push(`${i + 1}. ${m.name}`))
    lines.push('')
  }
  return lines
}

// Shared footer: Currently Have + attribution
function footerLines(checkedItems) {
  const lines = []
  if (checkedItems.length > 0) {
    lines.push('━━━━━━━━━━━━━━━━━━━━')
    lines.push('')
    lines.push('✅ Currently Have:')
    checkedItems.forEach(i => lines.push(`  - ${i}`))
    lines.push('')
  }
  lines.push('Generated by Mise en Place')
  return lines
}

// Copy All button format — plain ingredient names, no recipe breakdown
function buildCopyAllText(categories, manualItems, mealObjects, checked) {
  const lines = headerLines(getWeekRange(), mealObjects)
  const checkedItems = collectChecked(categories, manualItems, checked)

  Object.entries(categories).forEach(([cat, items]) => {
    const unchecked = items.filter(i => !checked.has(i))
    if (unchecked.length) {
      lines.push(`${cat}:`)
      unchecked.forEach(i => lines.push(`  - ${i}`))
      lines.push('')
    }
  })

  const uncheckedManual = manualItems.filter(m => !checked.has(m.name))
  if (uncheckedManual.length > 0) {
    lines.push('Other:')
    uncheckedManual.forEach(m => lines.push(`  • ${m.name}`))
    lines.push('')
  }

  return [...lines, ...footerLines(checkedItems)].join('\n')
}

// Full Ingredients modal format — consolidated total quantities per ingredient
function buildFullIngredientsText(categories, manualItems, mealObjects, consolidated, checked) {
  const lines = headerLines(getWeekRange(), mealObjects)
  const checkedItems = collectChecked(categories, manualItems, checked)

  Object.entries(categories).forEach(([cat, items]) => {
    const unchecked = items.filter(i => !checked.has(i))
    if (unchecked.length) {
      lines.push(`${cat}:`)
      unchecked.forEach(i => {
        let label = i
        if (consolidated === 'loading') label = `${i} …`
        else if (consolidated?.[i]) label = consolidated[i]
        lines.push(`  - ${label}`)
      })
      lines.push('')
    }
  })

  const uncheckedManual = manualItems.filter(m => !checked.has(m.name))
  if (uncheckedManual.length > 0) {
    lines.push('Other:')
    uncheckedManual.forEach(m => lines.push(`  • ${m.name}`))
    lines.push('')
  }

  return [...lines, ...footerLines(checkedItems)].join('\n')
}

// By Recipe modal format — category one-liners + per-recipe ingredient breakdown
function buildByRecipeText(categories, manualItems, mealObjects, quantities, checked) {
  const lines = headerLines(getWeekRange(), mealObjects)
  const checkedItems = collectChecked(categories, manualItems, checked)

  Object.entries(categories).forEach(([cat, items]) => {
    const unchecked = items.filter(i => !checked.has(i))
    if (unchecked.length) lines.push(`${cat}: ${unchecked.join(', ')}`)
  })

  lines.push('')
  lines.push('━━━━━━━━━━━━━━━━━━━━')
  lines.push('')
  lines.push('📋 By Recipe:')

  mealObjects.forEach(meal => {
    const enriched = Array.isArray(quantities[meal.id]) ? quantities[meal.id] : (meal.ingredients || [])
    const unchecked = enriched.filter(ing => !checked.has(ing))
    if (unchecked.length === 0) return
    lines.push('')
    lines.push(meal.name)
    unchecked.forEach(ing => lines.push(`  • ${ing}`))
  })

  const uncheckedManual = manualItems.filter(m => !checked.has(m.name))
  if (uncheckedManual.length > 0) {
    lines.push('')
    lines.push('Other:')
    uncheckedManual.forEach(m => lines.push(`  • ${m.name}`))
  }

  lines.push('')
  return [...lines, ...footerLines(checkedItems)].join('\n')
}

function ShoppingShareModal({ categories, manualItems, mealObjects, quantities, checked, onClose }) {
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState('fulling') // 'fulling' | 'byrecipe'
  const [consolidated, setConsolidated] = useState(null) // null | 'loading' | { [ing]: string }
  const consolidatedFetchedRef = useRef(false)

  useEffect(() => {
    const allIngredients = Object.values(categories).flat()
    if (allIngredients.length === 0) return
    if (consolidatedFetchedRef.current) return
    consolidatedFetchedRef.current = true
    setConsolidated('loading')
    const mealNames = mealObjects.map(m => m.name)
    consolidateQuantities(allIngredients, mealNames).then(result => {
      const map = {}
      allIngredients.forEach((ing, idx) => { map[ing] = result[idx] || ing })
      setConsolidated(map)
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fullIngredientsText = useMemo(
    () => buildFullIngredientsText(categories, manualItems, mealObjects, consolidated, checked),
    [categories, manualItems, mealObjects, consolidated, checked]
  )
  const byRecipeText = useMemo(
    () => buildByRecipeText(categories, manualItems, mealObjects, quantities, checked),
    [categories, manualItems, mealObjects, quantities, checked]
  )
  const text = format === 'fulling' ? fullIngredientsText : byRecipeText

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* ignore */ }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal modal-send slide-up" onClick={e => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>✕</button>
        <h2 className="modal-title">📤 Send / Share</h2>
        <div className="send-format-tabs">
          <button
            className={`send-format-tab ${format === 'fulling' ? 'active' : ''}`}
            onClick={() => { setFormat('fulling'); setCopied(false) }}
          >
            Full Ingredients
          </button>
          <button
            className={`send-format-tab ${format === 'byrecipe' ? 'active' : ''}`}
            onClick={() => { setFormat('byrecipe'); setCopied(false) }}
          >
            By Recipe
          </button>
        </div>
        {format === 'fulling' && consolidated === 'loading' && (
          <div className="send-consolidating">Consolidating quantities…</div>
        )}
        <pre className="send-preview">{text}</pre>
        <div className="send-actions">
          <button className="btn btn-primary" onClick={handleCopy}>
            {copied ? '✓ Copied!' : 'Copy to Clipboard'}
          </button>
          <button className="btn btn-secondary" onClick={() => window.open('sms:?body=' + encodeURIComponent(text))}>
            Open in Messages
          </button>
          <button className="btn btn-secondary" onClick={() => window.open('mailto:?subject=Shopping List&body=' + encodeURIComponent(text))}>
            Open in Email
          </button>
        </div>
      </div>
    </div>
  )
}

export default function Shopping({ weekMeals, loading, clearWeek }) {
  const weekStart = getWeekStart()
  const storageKey = `shop-checked-${weekStart}`
  const manualKey = `shop-manual-${weekStart}`

  const [checked, setChecked] = useState(() => {
    try { return new Set(JSON.parse(localStorage.getItem(storageKey) || '[]')) }
    catch { return new Set() }
  })
  const [copied, setCopied] = useState(false)
  const [quantities, setQuantities] = useState({})
  const [showSend, setShowSend] = useState(false)
  const [showClearConfirm, setShowClearConfirm] = useState(false)
  const [clearing, setClearing] = useState(false)
  const [manualInput, setManualInput] = useState('')
  const [manualItems, setManualItems] = useState(() => {
    try { return JSON.parse(localStorage.getItem(manualKey) || '[]') }
    catch { return [] }
  })
  const [pendingItems, setPendingItems] = useState([])
  const [catQuantities, setCatQuantities] = useState(null) // null | 'loading' | { [ing]: enrichedString }
  const fetchedRef = useRef(new Set())
  const catFetchedRef = useRef(new Set())

  const mealObjects = useMemo(() => weekMeals.map(wm => wm.meals).filter(Boolean), [weekMeals])
  const categories = useMemo(() => buildShoppingList(mealObjects), [mealObjects])

  const categoryIngsKey = useMemo(
    () => Object.values(categories).flat().join('|'),
    [categories]
  )

  const allCategoryKeys = useMemo(() => {
    const keys = new Set([
      ...Object.keys(categories),
      ...manualItems.map(m => m.category)
    ])
    return [
      ...CATEGORY_ORDER.filter(k => keys.has(k)),
      ...[...keys].filter(k => !CATEGORY_ORDER.includes(k))
    ]
  }, [categories, manualItems])

  const totalItems = Object.values(categories).reduce((sum, items) => sum + items.length, 0) + manualItems.length
  const totalCategories = allCategoryKeys.length + (pendingItems.length > 0 ? 1 : 0)

  useEffect(() => {
    localStorage.setItem(storageKey, JSON.stringify([...checked]))
  }, [checked, storageKey])

  // Fetch By Recipe quantities once per meal
  useEffect(() => {
    mealObjects.forEach(meal => {
      if (!meal.ingredients?.length) return
      if (fetchedRef.current.has(meal.id)) return
      fetchedRef.current.add(meal.id)
      setQuantities(prev => ({ ...prev, [meal.id]: 'loading' }))
      enrichIngredientsWithQuantities(meal.name, meal.ingredients).then(result => {
        setQuantities(prev => ({ ...prev, [meal.id]: result }))
      })
    })
  }, [mealObjects])

  // Fetch category quantities once per unique ingredient set
  useEffect(() => {
    const allIngredients = Object.values(categories).flat()
    if (allIngredients.length === 0) { setCatQuantities(null); return }
    if (catFetchedRef.current.has(categoryIngsKey)) return
    catFetchedRef.current.add(categoryIngsKey)
    setCatQuantities('loading')
    const mealNames = mealObjects.map(m => m.name).join(', ')
    enrichIngredientsWithQuantities(mealNames, allIngredients).then(result => {
      const map = {}
      allIngredients.forEach((ing, idx) => { map[ing] = result[idx] || ing })
      setCatQuantities(map)
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [categoryIngsKey])

  const toggleChecked = (item) => {
    setChecked(prev => {
      const next = new Set(prev)
      if (next.has(item)) next.delete(item)
      else next.add(item)
      return next
    })
  }

  const handleAddManual = () => {
    const val = manualInput.trim()
    if (!val) return
    setManualInput('')
    setPendingItems(prev => [...prev, val])
    categorizeIngredient(val).then(category => {
      setPendingItems(prev => prev.filter(p => p !== val))
      setManualItems(prev => {
        const next = [...prev, { name: val, category }]
        localStorage.setItem(manualKey, JSON.stringify(next))
        return next
      })
    })
  }

  const removeManualItem = (name) => {
    setManualItems(prev => {
      const next = prev.filter(m => m.name !== name)
      localStorage.setItem(manualKey, JSON.stringify(next))
      return next
    })
  }

  const handleClearAll = async () => {
    setClearing(true)
    try {
      await clearWeek()
      localStorage.removeItem(storageKey)
      localStorage.removeItem(manualKey)
      setChecked(new Set())
      setManualItems([])
      setCatQuantities(null)
      catFetchedRef.current.clear()
      setShowClearConfirm(false)
    } finally {
      setClearing(false)
    }
  }

  const allItemsText = useMemo(
    () => buildCopyAllText(categories, manualItems, mealObjects, checked),
    [categories, manualItems, mealObjects, checked]
  )

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(allItemsText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* ignore */ }
  }

  if (loading) {
    return (
      <div className="page">
        <div className="spinner-wrap"><div className="spinner" /></div>
      </div>
    )
  }

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Shopping List</h1>
          <p className="page-subtitle">Auto-generated from this week's meals. Check off items as you shop — your progress saves automatically and resets each new week.</p>
          <div className="week-header-meta">
            {totalItems} item{totalItems !== 1 ? 's' : ''} across {totalCategories} categor{totalCategories !== 1 ? 'ies' : 'y'}
            {' · '}{getWeekRange()}
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="shop-action-row">
        <button className="btn btn-secondary" onClick={() => setShowSend(true)} disabled={totalItems === 0}>
          📤 Send / Share
        </button>
        <button className="btn btn-secondary" onClick={handleCopyAll} disabled={totalItems === 0}>
          {copied ? '✓ Copied' : 'Copy All'}
        </button>
        <button
          className="btn btn-secondary"
          onClick={() => setShowClearConfirm(c => !c)}
          disabled={weekMeals.length === 0 && totalItems === 0}
        >
          🗑 Clear All
        </button>
      </div>
      <div className="shop-copy-note">Checked items are excluded from copy</div>

      {showClearConfirm && (
        <div className="shop-clear-confirm">
          <span className="shop-clear-text">This will remove all meals from This Week and clear the shopping list.</span>
          <div className="shop-clear-btns">
            <button className="btn btn-primary btn-sm" onClick={handleClearAll} disabled={clearing}>
              {clearing ? 'Clearing…' : 'Yes, Clear Everything'}
            </button>
            <button className="btn btn-ghost btn-sm" onClick={() => setShowClearConfirm(false)}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Manual ingredient input */}
      <div className="manual-add-row">
        <input
          className="form-input manual-add-input"
          value={manualInput}
          onChange={e => setManualInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleAddManual()}
          placeholder="Add an ingredient…"
        />
        <button className="btn btn-secondary" onClick={handleAddManual} disabled={!manualInput.trim()}>
          Add
        </button>
      </div>

      {totalItems === 0 && pendingItems.length === 0 ? (
        <div className="empty-state">
          <div className="empty-icon">🛒</div>
          <div className="empty-text">Add meals to This Week to generate your shopping list.</div>
        </div>
      ) : (
        <>
          {/* By Recipe — always expanded at top */}
          {mealObjects.length > 0 && (
            <div className="shop-section">
              <div className="shop-section-title">By Recipe</div>
              <div className="by-recipe-grid">
                {mealObjects.map(meal => {
                  const qData = quantities[meal.id]
                  const isLoading = qData === 'loading'
                  const enriched = Array.isArray(qData) ? qData : (meal.ingredients || [])

                  return (
                    <div key={meal.id} className="by-recipe-card card">
                      <div className="by-recipe-card-header">
                        <span className="by-recipe-card-name">{meal.name}</span>
                        {isLoading && <span className="qty-loading">Adding quantities…</span>}
                      </div>
                      <ul className="shop-item-list">
                        {enriched.map(ing => (
                          <li
                            key={ing}
                            className={`shop-item ${checked.has(ing) ? 'checked' : ''}`}
                            onClick={() => toggleChecked(ing)}
                          >
                            <span className="shop-checkbox">{checked.has(ing) ? '✓' : ''}</span>
                            <span className="shop-item-label">{ing}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )
                })}
              </div>
            </div>
          )}

          {/* All Items by Category */}
          <div className="shop-section">
            <div className="shop-section-title">All Items by Category</div>
            <div className="shop-grid">
              {allCategoryKeys.map(cat => {
                const autoItems = categories[cat] || []
                const manualForCat = manualItems.filter(m => m.category === cat)
                if (autoItems.length === 0 && manualForCat.length === 0) return null
                return (
                  <div key={cat} className="shop-card card">
                    <div className="shop-card-title">{cat}</div>
                    <ul className="shop-item-list">
                      {autoItems.map(item => {
                        const displayLabel = catQuantities && catQuantities !== 'loading' && catQuantities[item]
                          ? catQuantities[item]
                          : item
                        return (
                          <li
                            key={item}
                            className={`shop-item ${checked.has(item) ? 'checked' : ''}`}
                            onClick={() => toggleChecked(item)}
                          >
                            <span className="shop-checkbox">{checked.has(item) ? '✓' : ''}</span>
                            <span className="shop-item-label">
                              {displayLabel}
                              {catQuantities === 'loading' && (
                                <span className="cat-qty-dot"> …</span>
                              )}
                            </span>
                          </li>
                        )
                      })}
                      {manualForCat.map(item => (
                        <li
                          key={item.name}
                          className={`shop-item shop-item-manual ${checked.has(item.name) ? 'checked' : ''}`}
                          onClick={() => toggleChecked(item.name)}
                        >
                          <span className="shop-checkbox">{checked.has(item.name) ? '✓' : ''}</span>
                          <span className="shop-item-label">{item.name}</span>
                          <span className="badge-added">+ added</span>
                          <button
                            className="shop-item-remove"
                            onClick={e => { e.stopPropagation(); removeManualItem(item.name) }}
                          >×</button>
                        </li>
                      ))}
                    </ul>
                  </div>
                )
              })}

              {/* Uncategorized — pending AI response */}
              {pendingItems.length > 0 && (
                <div className="shop-card card">
                  <div className="shop-card-title">Uncategorized</div>
                  <ul className="shop-item-list">
                    {pendingItems.map(item => (
                      <li key={item} className="shop-item">
                        <span className="shop-checkbox" />
                        <span className="shop-item-label">{item}</span>
                        <span className="badge-added qty-loading">categorizing…</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        </>
      )}

      {showSend && (
        <ShoppingShareModal
          categories={categories}
          manualItems={manualItems}
          mealObjects={mealObjects}
          quantities={quantities}
          checked={checked}
          onClose={() => setShowSend(false)}
        />
      )}
    </div>
  )
}
