import { useState, useEffect, useRef, useMemo } from 'react'
import { buildShoppingList, enrichIngredientsWithQuantities, categorizeIngredient, consolidateQuantities } from '../utils/shopping'
import { getWeekRange, getWeekStart } from '../utils/format'
import { useShoppingItems } from '../hooks/useShoppingItems'
import { scaleIngredientsByFactor } from '../utils/scaling'

const SCALE_OPTIONS = [
  { factor: 0.5, label: '½×' },
  { factor: 1,   label: '1×' },
  { factor: 2,   label: '2×' },
]

function getStoredFactor(wmId) {
  const saved = localStorage.getItem(`scale-factor-${wmId}`)
  return saved ? parseFloat(saved) : 1
}

function storeFactor(wmId, factor) {
  if (factor === 1) localStorage.removeItem(`scale-factor-${wmId}`)
  else localStorage.setItem(`scale-factor-${wmId}`, String(factor))
}

const CATEGORY_ORDER = [
  'Proteins & Meat', 'Seafood', 'Produce', 'Dairy & Eggs',
  'Pantry & Dry Goods', 'Herbs & Spices', 'Other'
]

// Collect every item the user has marked checked
function collectChecked(checked) {
  return [...checked]
}

// Shared header: date + numbered meal list
function headerLines(range, mealObjects) {
  const lines = [`🛒 Shopping List — ${range}`, '']
  if (mealObjects.length > 0) {
    lines.push("🍽️ This Week's Meals:")
    mealObjects.forEach((m, i) => lines.push(`${i + 1}. ${m.name}`))
    lines.push('')
  }
  return lines
}

// Shared footer: Currently Have (no ━━━ divider) + attribution
function footerLines(checkedItems) {
  const lines = []
  if (checkedItems.length > 0) {
    lines.push('Currently Have:')
    checkedItems.forEach(i => lines.push(`- ${i}`))
    lines.push('')
  }
  lines.push('Generated by Rouxlo')
  return lines
}

// Build the merged Other block: auto-categorized Other items + unchecked manual items
// Returns null if nothing to show, otherwise { items: string[] }
function mergedOther(categories, manualItems, checked) {
  const autoOther = (categories['Other'] || []).filter(i => !checked.has(i))
  const uncheckedManual = manualItems.filter(m => !checked.has(m.name)).map(m => m.name)
  const all = [...new Set([...autoOther, ...uncheckedManual])]
  return all.length > 0 ? all : null
}

// Copy All button format — enriched quantities, merged Other, Currently Have at bottom
function buildCopyAllText(categories, manualItems, mealObjects, checked, catQuantities) {
  const lines = headerLines(getWeekRange(), mealObjects)
  const checkedItems = collectChecked(checked)

  const label = (i) => {
    if (!catQuantities || catQuantities === 'loading') return i
    return catQuantities[i] || i
  }

  CATEGORY_ORDER.forEach(cat => {
    if (cat === 'Other') return // handled below
    const items = (categories[cat] || []).filter(i => !checked.has(i))
    if (items.length) {
      lines.push(`${cat}:`)
      items.forEach(i => lines.push(`  • ${label(i)}`))
      lines.push('')
    }
  })
  // Any categories not in the ordered list
  Object.keys(categories)
    .filter(k => !CATEGORY_ORDER.includes(k))
    .forEach(cat => {
      const items = categories[cat].filter(i => !checked.has(i))
      if (items.length) {
        lines.push(`${cat}:`)
        items.forEach(i => lines.push(`  • ${label(i)}`))
        lines.push('')
      }
    })

  // Single merged Other block: auto-Other + unchecked manual
  const autoOther = (categories['Other'] || []).filter(i => !checked.has(i))
  const uncheckedManual = manualItems.filter(m => !checked.has(m.name)).map(m => m.name)
  const allOther = [...new Set([...autoOther, ...uncheckedManual])]
  if (allOther.length > 0) {
    lines.push('Other:')
    allOther.forEach(i => lines.push(`  • ${i}`))
    lines.push('')
  }

  // Currently Have
  if (checkedItems.length > 0) {
    lines.push('Currently Have:')
    checkedItems.forEach(i => lines.push(`  • ${i}`))
    lines.push('')
  }

  lines.push('Generated by Rouxlo')
  return lines.join('\n')
}

// Full Ingredients format — consolidated quantities, merged Other, Currently Have
function buildFullIngredientsText(categories, manualItems, mealObjects, consolidated, checked) {
  const lines = headerLines(getWeekRange(), mealObjects)
  const checkedItems = collectChecked(checked)

  const label = (i) => {
    if (consolidated === 'loading') return `${i} …`
    return consolidated?.[i] || i
  }

  CATEGORY_ORDER.forEach(cat => {
    if (cat === 'Other') return
    const items = (categories[cat] || []).filter(i => !checked.has(i))
    if (items.length) {
      lines.push(`${cat}:`)
      items.forEach(i => lines.push(`  - ${label(i)}`))
      lines.push('')
    }
  })
  Object.keys(categories)
    .filter(k => !CATEGORY_ORDER.includes(k))
    .forEach(cat => {
      const items = categories[cat].filter(i => !checked.has(i))
      if (items.length) {
        lines.push(`${cat}:`)
        items.forEach(i => lines.push(`  - ${label(i)}`))
        lines.push('')
      }
    })

  const other = mergedOther(categories, manualItems, checked)
  if (other) {
    lines.push('Other:')
    other.forEach(i => lines.push(`  - ${label(i)}`))
    lines.push('')
  }

  return [...lines, ...footerLines(checkedItems)].join('\n')
}

// By Recipe format — all ingredients under their meal, checked items get ✓ prefix, no Currently Have
function buildByRecipeText(categories, manualItems, mealObjects, quantities, checked) {
  const lines = headerLines(getWeekRange(), mealObjects)

  mealObjects.forEach(meal => {
    const enriched = Array.isArray(quantities[meal.id]) ? quantities[meal.id] : (meal.ingredients || [])
    const unchecked = enriched.filter(ing => !checked.has(ing))
    const checkedForMeal = enriched.filter(ing => checked.has(ing))
    if (unchecked.length === 0 && checkedForMeal.length === 0) return
    lines.push(`${meal.name}:`)
    unchecked.forEach(ing => lines.push(`  - ${ing}`))
    checkedForMeal.forEach(ing => lines.push(`  ✓ ${ing}`))
    lines.push('')
  })

  // Other: manually added items — unchecked first with •, checked with ✓
  const uncheckedManual = manualItems.filter(m => !checked.has(m.name))
  const checkedManual = manualItems.filter(m => checked.has(m.name))
  if (uncheckedManual.length > 0 || checkedManual.length > 0) {
    lines.push('Other:')
    uncheckedManual.forEach(m => lines.push(`  • ${m.name}`))
    checkedManual.forEach(m => lines.push(`  ✓ ${m.name}`))
    lines.push('')
  }

  lines.push('Generated by Rouxlo')
  return lines.join('\n')
}

function ShoppingShareModal({ categories, manualItems, mealObjects, quantities, checked, onClose }) {
  const [copied, setCopied] = useState(false)
  const [format, setFormat] = useState('fulling') // 'fulling' | 'byrecipe'
  const [consolidated, setConsolidated] = useState(null) // null | 'loading' | { [ing]: string }
  const consolidatedFetchedRef = useRef(false)

  useEffect(() => {
    const allIngredients = Object.values(categories).flat()
    if (allIngredients.length === 0) return
    if (consolidatedFetchedRef.current) return
    consolidatedFetchedRef.current = true
    setConsolidated('loading')
    const mealNames = mealObjects.map(m => m.name)
    consolidateQuantities(allIngredients, mealNames).then(result => {
      const map = {}
      allIngredients.forEach((ing, idx) => { map[ing] = result[idx] || ing })
      setConsolidated(map)
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fullIngredientsText = useMemo(
    () => buildFullIngredientsText(categories, manualItems, mealObjects, consolidated, checked),
    [categories, manualItems, mealObjects, consolidated, checked]
  )
  const byRecipeText = useMemo(
    () => buildByRecipeText(categories, manualItems, mealObjects, quantities, checked),
    [categories, manualItems, mealObjects, quantities, checked]
  )
  const text = format === 'fulling' ? fullIngredientsText : byRecipeText

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* ignore */ }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal modal-send slide-up" onClick={e => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>✕</button>
        <h2 className="modal-title">📤 Send / Share</h2>
        <div className="send-format-tabs">
          <button
            className={`send-format-tab ${format === 'fulling' ? 'active' : ''}`}
            onClick={() => { setFormat('fulling'); setCopied(false) }}
          >
            Full Ingredients
          </button>
          <button
            className={`send-format-tab ${format === 'byrecipe' ? 'active' : ''}`}
            onClick={() => { setFormat('byrecipe'); setCopied(false) }}
          >
            By Recipe
          </button>
        </div>
        {format === 'fulling' && consolidated === 'loading' && (
          <div className="send-consolidating">Consolidating quantities…</div>
        )}
        <pre className="send-preview">{text}</pre>
        <div className="send-actions">
          <button className="btn btn-primary" onClick={handleCopy}>
            {copied ? '✓ Copied!' : 'Copy to Clipboard'}
          </button>
          <button className="btn btn-secondary" onClick={() => window.open('sms:?body=' + encodeURIComponent(text))}>
            Open in Messages
          </button>
          <button className="btn btn-secondary" onClick={() => window.open('mailto:?subject=Shopping List&body=' + encodeURIComponent(text))}>
            Open in Email
          </button>
        </div>
      </div>
    </div>
  )
}

export default function Shopping({ weekMeals, loading, clearWeek }) {
  const weekStart = getWeekStart()
  const [scaleFactors, setScaleFactors] = useState({})

  const {
    recipeChecked,
    manualItems,
    toggleRecipeIng,
    toggleCategoryIng,
    toggleManual,
    addManualItem,
    removeManualItem,
    clearAllItems,
  } = useShoppingItems()

  const [collapsed, setCollapsed] = useState(() => {
    try { return JSON.parse(localStorage.getItem('shop-collapsed') || '{}') }
    catch { return {} }
  })
  const [collapsedRecipes, setCollapsedRecipes] = useState(new Set())
  const [copied, setCopied] = useState(false)
  const [quantities, setQuantities] = useState({})
  const [showSend, setShowSend] = useState(false)
  const [showClearConfirm, setShowClearConfirm] = useState(false)
  const [clearing, setClearing] = useState(false)
  const [manualInput, setManualInput] = useState('')
  const [pendingItems, setPendingItems] = useState([])
  const [catQuantities, setCatQuantities] = useState(null) // null | 'loading' | { [ing]: enrichedString }
  const fetchedRef = useRef(new Set())
  const catFetchedRef = useRef(new Set())

  useEffect(() => {
    const loaded = {}
    weekMeals.forEach(wm => {
      const f = getStoredFactor(wm.id)
      if (f !== 1) loaded[wm.id] = f
    })
    setScaleFactors(loaded)
  }, [weekMeals])

  const setWmFactor = (wmId, factor) => {
    storeFactor(wmId, factor)
    setScaleFactors(prev => ({ ...prev, [wmId]: factor }))
  }

  const mealObjects = useMemo(() => weekMeals.map(wm => wm.meals).filter(Boolean), [weekMeals])

  const scaledMealObjects = useMemo(() => weekMeals.map(wm => {
    const m = wm.meals
    if (!m) return null
    const factor = scaleFactors[wm.id] ?? 1
    if (factor === 1) return m
    return { ...m, ingredients: scaleIngredientsByFactor(m.ingredients || [], factor) }
  }).filter(Boolean), [weekMeals, scaleFactors])

  const categories = useMemo(() => buildShoppingList(scaledMealObjects), [scaledMealObjects])

  const categoryIngsKey = useMemo(
    () => Object.values(categories).flat().join('|'),
    [categories]
  )

  const allCategoryKeys = useMemo(() => {
    const keys = new Set([
      ...Object.keys(categories),
      ...manualItems.map(m => m.category)
    ])
    return [
      ...CATEGORY_ORDER.filter(k => keys.has(k)),
      ...[...keys].filter(k => !CATEGORY_ORDER.includes(k))
    ]
  }, [categories, manualItems])

  const totalItems = Object.values(categories).reduce((sum, items) => sum + items.length, 0) + manualItems.length
  const totalCategories = allCategoryKeys.length + (pendingItems.length > 0 ? 1 : 0)

  // Fetch By Recipe quantities once per meal
  useEffect(() => {
    mealObjects.forEach(meal => {
      if (!meal.ingredients?.length) return
      if (fetchedRef.current.has(meal.id)) return
      fetchedRef.current.add(meal.id)
      setQuantities(prev => ({ ...prev, [meal.id]: 'loading' }))
      enrichIngredientsWithQuantities(meal.name, meal.ingredients).then(result => {
        setQuantities(prev => ({ ...prev, [meal.id]: result }))
      })
    })
  }, [mealObjects])

  // Fetch category quantities once per unique ingredient set
  useEffect(() => {
    const allIngredients = Object.values(categories).flat()
    if (allIngredients.length === 0) { setCatQuantities(null); return }
    if (catFetchedRef.current.has(categoryIngsKey)) return
    catFetchedRef.current.add(categoryIngsKey)
    setCatQuantities('loading')
    const mealNames = mealObjects.map(m => m.name).join(', ')
    enrichIngredientsWithQuantities(mealNames, allIngredients).then(result => {
      const map = {}
      allIngredients.forEach((ing, idx) => { map[ing] = result[idx] || ing })
      setCatQuantities(map)
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [categoryIngsKey])

  const toggleSection = (key) => {
    setCollapsed(prev => {
      const next = { ...prev, [key]: !prev[key] }
      localStorage.setItem('shop-collapsed', JSON.stringify(next))
      return next
    })
  }

  const toggleRecipe = (id) => {
    setCollapsedRecipes(prev => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const normIng = (s) => s.toLowerCase().trim()

  const isRecipeIngChecked = (mealId, origIng) =>
    recipeChecked.has(`${mealId}|||${origIng}`)

  const isCategoryIngChecked = (ing) => {
    const norm = normIng(ing)
    const meals = mealObjects.filter(m =>
      (m.ingredients || []).some(i => normIng(i) === norm)
    )
    if (meals.length === 0) return false
    return meals.every(m => {
      const orig = (m.ingredients || []).find(i => normIng(i) === norm)
      return orig && recipeChecked.has(`${m.id}|||${orig}`)
    })
  }

  const isManualChecked = (name) => recipeChecked.has(`manual|||${name}`)

  const handleToggleCategoryIng = (ing) => toggleCategoryIng(ing, mealObjects)

  // Derive a flat "fully checked" set for copy/share functions
  const effectiveChecked = useMemo(() => {
    const result = new Set()
    Object.values(categories).flat().forEach(ing => {
      if (isCategoryIngChecked(ing)) result.add(ing)
    })
    manualItems.forEach(m => { if (isManualChecked(m.name)) result.add(m.name) })
    return result
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [categories, manualItems, recipeChecked, mealObjects])

  const handleAddManual = () => {
    const val = manualInput.trim()
    if (!val) return
    setManualInput('')
    setPendingItems(prev => [...prev, val])
    categorizeIngredient(val).then(category => {
      setPendingItems(prev => prev.filter(p => p !== val))
      addManualItem(val, category)
    })
  }

  const handleClearAll = async () => {
    setClearing(true)
    try {
      await clearWeek()
      await clearAllItems()
      setCatQuantities(null)
      catFetchedRef.current.clear()
      setShowClearConfirm(false)
    } finally {
      setClearing(false)
    }
  }

  const allItemsText = useMemo(
    () => buildCopyAllText(categories, manualItems, mealObjects, effectiveChecked, catQuantities),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [categories, manualItems, mealObjects, effectiveChecked, catQuantities]
  )

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(allItemsText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* ignore */ }
  }

  if (loading) {
    return (
      <div className="page">
        <div className="spinner-wrap"><div className="spinner" /></div>
      </div>
    )
  }

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Shopping List</h1>
          <p className="page-subtitle">Auto-generated from this week's meals. Check off items as you shop — your progress saves automatically and resets each new week.</p>
          <div className="week-header-meta">
            {totalItems} item{totalItems !== 1 ? 's' : ''} across {totalCategories} categor{totalCategories !== 1 ? 'ies' : 'y'}
            {' · '}{getWeekRange()}
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="shop-action-row">
        <button className="btn btn-secondary" onClick={() => setShowSend(true)} disabled={totalItems === 0}>
          📤 Send / Share
        </button>
        <button className="btn btn-secondary" onClick={handleCopyAll} disabled={totalItems === 0}>
          {copied ? '✓ Copied' : 'Copy All'}
        </button>
        <button
          className="btn btn-secondary"
          onClick={() => setShowClearConfirm(c => !c)}
          disabled={weekMeals.length === 0 && totalItems === 0}
        >
          🗑 Clear All
        </button>
      </div>
      <div className="shop-copy-note">Checked items appear under Currently Have</div>

      {showClearConfirm && (
        <div className="shop-clear-confirm">
          <span className="shop-clear-text">This will remove all meals from This Week and clear the shopping list.</span>
          <div className="shop-clear-btns">
            <button className="btn btn-primary btn-sm" onClick={handleClearAll} disabled={clearing}>
              {clearing ? 'Clearing…' : 'Yes, Clear Everything'}
            </button>
            <button className="btn btn-ghost btn-sm" onClick={() => setShowClearConfirm(false)}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Manual ingredient input */}
      <div className="manual-add-row">
        <input
          className="form-input manual-add-input"
          value={manualInput}
          onChange={e => setManualInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleAddManual()}
          placeholder="Add an ingredient…"
        />
        <button className="btn btn-secondary" onClick={handleAddManual} disabled={!manualInput.trim()}>
          Add
        </button>
      </div>

      {totalItems === 0 && pendingItems.length === 0 ? (
        <div className="empty-state">
          <div className="empty-icon">🛒</div>
          <div className="empty-text">Add meals to This Week to generate your shopping list.</div>
        </div>
      ) : (
        <>
          {/* By Recipe */}
          {mealObjects.length > 0 && (
            <div className="shop-section">
              <button className="shop-section-title shop-section-toggle" onClick={() => toggleSection('byRecipe')}>
                By Recipe
                <span className="shop-section-chevron">{collapsed.byRecipe ? '▸' : '▾'}</span>
              </button>
              {!collapsed.byRecipe && <div className="by-recipe-grid">
                {mealObjects.map(meal => {
                  const wm = weekMeals.find(w => w.meal_id === meal.id)
                  const factor = scaleFactors[wm?.id] ?? 1
                  const origIngredients = meal.ingredients || []
                  const displayIngredients = factor !== 1
                    ? scaleIngredientsByFactor(origIngredients, factor)
                    : origIngredients
                  const qData = quantities[meal.id]
                  const isLoading = qData === 'loading'
                  const isRecipeCollapsed = collapsedRecipes.has(meal.id)

                  return (
                    <div key={meal.id} className="by-recipe-card card">
                      <div className="by-recipe-card-header">
                        <button
                          className="by-recipe-card-toggle"
                          onClick={() => toggleRecipe(meal.id)}
                        >
                          <span className="by-recipe-card-name">{meal.name}</span>
                          <span className="shop-section-chevron">{isRecipeCollapsed ? '▸' : '▾'}</span>
                        </button>
                        {wm && (
                          <div className="scale-toggle" onClick={e => e.stopPropagation()}>
                            {SCALE_OPTIONS.map(({ factor: f, label }) => (
                              <button
                                key={f}
                                className={`scale-toggle-btn${factor === f ? ' active' : ''}`}
                                onClick={() => setWmFactor(wm.id, f)}
                              >{label}</button>
                            ))}
                          </div>
                        )}
                      </div>
                      {/* Source link and/or photo thumbnails */}
                      {(meal.source || meal.photo_urls?.length > 0 || meal.photo_url) && (
                        <div className="by-recipe-links" onClick={e => e.stopPropagation()}>
                          {meal.source && (
                            <a
                              href={meal.source}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="by-recipe-source-link"
                            >
                              ↗ View recipe
                            </a>
                          )}
                          {(meal.photo_urls?.length > 0 || meal.photo_url) && (
                            <div className="by-recipe-photos">
                              {(meal.photo_urls?.length > 0 ? meal.photo_urls : [meal.photo_url]).map((url, i) => (
                                <a key={i} href={url} target="_blank" rel="noopener noreferrer">
                                  <img src={url} alt={`${meal.name} page ${i + 1}`} className="by-recipe-photo-thumb" />
                                </a>
                              ))}
                            </div>
                          )}
                        </div>
                      )}
                      {!isRecipeCollapsed && (
                        <ul className="shop-item-list">
                          {isLoading && factor === 1 && <li className="shop-item"><span className="qty-loading">Adding quantities…</span></li>}
                          {displayIngredients.map((dispIng, i) => {
                            const origIng = origIngredients[i] || dispIng
                            const label = (factor === 1 && Array.isArray(qData) && qData[i]) ? qData[i] : dispIng
                            const isChecked = isRecipeIngChecked(meal.id, origIng)
                            return (
                              <li
                                key={origIng + i}
                                className={`shop-item ${isChecked ? 'checked' : ''}`}
                                onClick={() => toggleRecipeIng(meal.id, origIng)}
                              >
                                <span className="shop-checkbox">{isChecked ? '✓' : ''}</span>
                                <span className="shop-item-label">{label}</span>
                              </li>
                            )
                          })}
                        </ul>
                      )}
                    </div>
                  )
                })}
              </div>}
            </div>
          )}

          {/* All Items by Category */}
          <div className="shop-section">
            <button className="shop-section-title shop-section-toggle" onClick={() => toggleSection('byCategory')}>
              All Items by Category
              <span className="shop-section-chevron">{collapsed.byCategory ? '▸' : '▾'}</span>
            </button>
            {!collapsed.byCategory && <div className="shop-grid">
              {allCategoryKeys.map(cat => {
                const autoItems = categories[cat] || []
                const manualForCat = manualItems.filter(m => m.category === cat)
                if (autoItems.length === 0 && manualForCat.length === 0) return null
                return (
                  <div key={cat} className="shop-card card">
                    <div className="shop-card-title">{cat}</div>
                    <ul className="shop-item-list">
                      {autoItems.map(item => {
                        const displayLabel = catQuantities && catQuantities !== 'loading' && catQuantities[item]
                          ? catQuantities[item]
                          : item
                        const isChecked = isCategoryIngChecked(item)
                        return (
                          <li
                            key={item}
                            className={`shop-item ${isChecked ? 'checked' : ''}`}
                            onClick={() => handleToggleCategoryIng(item)}
                          >
                            <span className="shop-checkbox">{isChecked ? '✓' : ''}</span>
                            <span className="shop-item-label">
                              {displayLabel}
                              {catQuantities === 'loading' && (
                                <span className="cat-qty-dot"> …</span>
                              )}
                            </span>
                          </li>
                        )
                      })}
                      {manualForCat.map(item => (
                        <li
                          key={item.name}
                          className={`shop-item shop-item-manual ${isManualChecked(item.name) ? 'checked' : ''}`}
                          onClick={() => toggleManual(item.name)}
                        >
                          <span className="shop-checkbox">{isManualChecked(item.name) ? '✓' : ''}</span>
                          <span className="shop-item-label">{item.name}</span>
                          <span className="badge-added">+ added</span>
                          <button
                            className="shop-item-remove"
                            onClick={e => { e.stopPropagation(); removeManualItem(item.name) }}
                          >×</button>
                        </li>
                      ))}
                    </ul>
                  </div>
                )
              })}

              {/* Uncategorized — pending AI response */}
              {pendingItems.length > 0 && (
                <div className="shop-card card">
                  <div className="shop-card-title">Uncategorized</div>
                  <ul className="shop-item-list">
                    {pendingItems.map(item => (
                      <li key={item} className="shop-item">
                        <span className="shop-checkbox" />
                        <span className="shop-item-label">{item}</span>
                        <span className="badge-added qty-loading">categorizing…</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>}
          </div>
        </>
      )}

      {showSend && (
        <ShoppingShareModal
          categories={categories}
          manualItems={manualItems}
          mealObjects={mealObjects}
          quantities={quantities}
          checked={effectiveChecked}
          onClose={() => setShowSend(false)}
        />
      )}
    </div>
  )
}
