import { useState } from 'react'
import { buildShoppingList } from '../utils/shopping'
import { getWeekRange } from '../utils/format'

function formatMealText(weekMeals) {
  const range = getWeekRange()
  const lines = [`🍽️ Meals This Week (${range})`, '']

  weekMeals.forEach((wm, i) => {
    const m = wm.meals
    lines.push(`${i + 1}. ${m.name}`)
    lines.push(`   ⭐ ${m.rating}/5 · Cooked ${m.times_made}×`)
    if (m.ingredients?.length) {
      lines.push(`   Ingredients: ${m.ingredients.join(', ')}`)
    }
    if (m.notes) lines.push(`   📝 ${m.notes}`)
    if (m.source) lines.push(`   🔗 ${m.source}`)
    lines.push('')
  })

  lines.push('━━━━━━━━━━━━━━━━━━━━')
  lines.push('')
  lines.push('🛒 Shopping List')
  lines.push('')

  const mealObjects = weekMeals.map(wm => wm.meals)
  const categories = buildShoppingList(mealObjects)
  for (const [cat, items] of Object.entries(categories)) {
    lines.push(`${cat}: ${items.join(', ')}`)
  }

  lines.push('')
  lines.push('Generated by Rouxlo')

  return lines.join('\n')
}

export default function SendModal({ weekMeals, onClose }) {
  const [copied, setCopied] = useState(false)
  const text = formatMealText(weekMeals)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback: select the textarea
    }
  }

  const handleMessages = () => {
    window.open('sms:?body=' + encodeURIComponent(text))
  }

  const handleEmail = () => {
    window.open('mailto:?subject=Meals This Week&body=' + encodeURIComponent(text))
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal modal-send slide-up" onClick={e => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>✕</button>
        <h2 className="modal-title">📤 Send / Share</h2>

        <pre className="send-preview">{text}</pre>

        <div className="send-actions">
          <button className="btn btn-primary" onClick={handleCopy}>
            {copied ? '✓ Copied!' : 'Copy to Clipboard'}
          </button>
          <button className="btn btn-secondary" onClick={handleMessages}>
            Open in Messages
          </button>
          <button className="btn btn-secondary" onClick={handleEmail}>
            Open in Email
          </button>
        </div>
      </div>
    </div>
  )
}
